### ISSUE TITLE
Motion Detector Alarm Status

### ISSUE THREAD

**Issue by panarom** [jhaines0/HoneywellSecurity#4]
https://github.com/jhaines0/HoneywellSecurity/blob/18a4ac82e79cca532b1eadb33327d49a73ce7df1/rpi/digitalDecoder.cpp#L78

If the sensor is identified as a motion detector based on the state being less than 0x80, won't testing state & 0x80 for alarm status always return 0?

**Comment by jhaines0** [comment]
This code is a bit funny... If a status comes through that is < 0x80 then the device ID is marked as a motion detector. Then in subsequent messages the device is known as a motion detector and the alarm bit is decoded appropriately. You're correct that these two conditions will never be both true for the same status message, but the code still works as desired.  The meaning of these bits was reverse engineered, so the logic is complicated. Check out the post here for more info on the bit semantics: https://github.com/jhaines0/HoneywellSecurity/issues/2
